# Generated by Django 5.2 on 2025-05-19 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('tasks', '0004_mention'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_mention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_for_mention', to='tasks.mention', verbose_name='Related Mention'),
        ),
    ]
