# Generated by Django 5.2 on 2025-04-22 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskhistory',
            name='task',
        ),
        migrations.RemoveField(
            model_name='taskhistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='TaskHistory',
        ),
    ]
